### ISSUE TITLE
As a developer, I need to make the video player work in every orientation

### ISSUE THREAD

**Issue by Abdullahejaz** [antishake/antishake_android#61]

**Comment by Abdullahejaz** [comment]
now the video is not getting started from the beginning when the orientation changes. Review it so that can move it to done.

**Comment by ruraj** [comment]
@Abdullahejaz, that is great. But the video seems to get stretched when in portrait mode. Can you check?

**Comment by Abdullahejaz** [comment]
Okay. I will look into the issue

**Comment by Abdullahejaz** [comment]
This is done and as everyone reviewed it, and voted it as done. I am closing it

**Comment by Abdullahejaz** [comment]
pull request has been approved. Moving it to done.
